# Generated by Django 3.2.9 on 2021-12-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('isbn', models.CharField(max_length=13)),
                ('pages', models.PositiveSmallIntegerField()),
                ('cover', models.URLField()),
                ('language', models.CharField(max_length=25)),
            ],
        ),
    ]
