# Generated by Django 3.2.9 on 2021-11-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('isbn', models.PositiveIntegerField()),
                ('pages', models.PositiveSmallIntegerField()),
                ('cover', models.URLField()),
                ('language', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
